# Generated by Django 3.2.13 on 2023-03-17 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opscentre_usermanagement_api', '0003_auto_20230317_2031'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='opsteam',
            table='OpsTeam',
        ),
    ]
