# Generated by Django 3.2.13 on 2023-03-17 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opscentre_usermanagement_api', '0004_alter_opsteams_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='opsteam',
            options={'base_manager_name': 'base_manager', 'verbose_name': 'OpsTeam', 'verbose_name_plural': 'OpsTeams'},
        ),
        migrations.AlterModelTable(
            name='opsteam',
            table='OpsTeam__c',
        ),
    ]
