# Generated by Django 3.2.13 on 2023-03-21 08:38

from django.db import migrations
import django.db.models.deletion
import django.db.models.manager
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opscentre_usermanagement_api', '0006_servicerq_sr_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpsRole',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('role', salesforce.fields.CharField(db_column='Name', max_length=80, unique=True)),
            ],
            options={
                'verbose_name': 'OpsRole',
                'verbose_name_plural': 'OpsRoles',
                'db_table': 'OpsRole__c',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='opsteam',
            name='OpsRole',
            field=salesforce.fields.ForeignKey(db_column='OpsRole__c', on_delete=django.db.models.deletion.DO_NOTHING, to='opscentre_usermanagement_api.opsrole'),
        ),
    ]
