# Generated by Django 3.2.13 on 2023-03-23 21:21

from django.db import migrations
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opscentre_usermanagement_api', '0007_auto_20230321_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsteam',
            name='first_name',
            field=salesforce.fields.CharField(db_column='first_name__c', default=salesforce.fields.DefaultedOnCreate(), max_length=255),
        ),
        migrations.AddField(
            model_name='opsteam',
            name='last_name',
            field=salesforce.fields.CharField(db_column='last_name__c', default=salesforce.fields.DefaultedOnCreate(), max_length=255),
        ),
    ]
