# Generated by Django 3.2.13 on 2023-03-31 09:57

from django.db import migrations
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opscentre_usermanagement_api', '0008_auto_20230324_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='opsrole',
            old_name='role',
            new_name='name',
        ),
        migrations.AddField(
            model_name='opsrole',
            name='record_id',
            field=salesforce.fields.CharField(blank=True, db_column='Id__c', max_length=1300),
        ),
    ]
