# Generated by Django 3.2.13 on 2023-03-31 14:17

from django.db import migrations
import django.db.models.deletion
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opscentre_usermanagement_api', '0014_auto_20230331_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opsteam',
            name='OpsRole',
            field=salesforce.fields.ForeignKey(db_column='OpsTeamRole__c', on_delete=django.db.models.deletion.DO_NOTHING, to='opscentre_usermanagement_api.opsteamrole', verbose_name='OpsTeamRole'),
        ),
    ]
