# Generated by Django 3.2.13 on 2023-03-31 22:11

from django.db import migrations
import django.db.models.deletion
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement_api', '0003_candidateprofile_cand_id'),
        ('auction_api', '0002_auction_cand_id'),
        ('opscentre_usermanagement_api', '0017_auto_20230401_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerq',
            name='assigned_to',
            field=salesforce.fields.ForeignKey(blank=True, db_column='OpsTeam__c', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='opscentre_usermanagement_api.opsteam'),
        ),
        migrations.AlterField(
            model_name='servicerq',
            name='auction',
            field=salesforce.fields.ForeignKey(blank=True, db_column='Auction__c', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='auction_api.auction'),
        ),
        migrations.AlterField(
            model_name='servicerq',
            name='candidate',
            field=salesforce.fields.ForeignKey(blank=True, db_column='Candidate__c', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermanagement_api.candidate'),
        ),
        migrations.AlterField(
            model_name='servicerq',
            name='detailed_notes',
            field=salesforce.fields.TextField(blank=True, db_column='DetailedNotes__c', null=True),
        ),
        migrations.AlterField(
            model_name='servicerq',
            name='recruiter',
            field=salesforce.fields.ForeignKey(blank=True, db_column='ContactId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermanagement_api.contact', verbose_name='Contact ID'),
        ),
        migrations.AlterField(
            model_name='servicerq',
            name='status',
            field=salesforce.fields.CharField(choices=[('Open', 'Open'), ('In-progress', 'In-progress'), ('Resolved', 'Resolved')], db_column='Status__c', max_length=255, verbose_name='Status'),
        ),
    ]
