# Generated by Django 3.2.13 on 2023-03-31 22:47

from django.db import migrations
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opscentre_usermanagement_api', '0020_alter_servicerq_recruiter'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerq',
            old_name='assigned_to',
            new_name='opsteam',
        ),
        migrations.AddField(
            model_name='servicerq',
            name='auc_id',
            field=salesforce.fields.CharField(blank=True, db_column='auc_Id__c', max_length=1300),
        ),
        migrations.AddField(
            model_name='servicerq',
            name='cand_id',
            field=salesforce.fields.CharField(blank=True, db_column='cand_id__c', max_length=1300),
        ),
        migrations.AddField(
            model_name='servicerq',
            name='ops_id',
            field=salesforce.fields.CharField(blank=True, db_column='Ops_id__c', max_length=1300),
        ),
        migrations.AddField(
            model_name='servicerq',
            name='rec_id',
            field=salesforce.fields.CharField(blank=True, db_column='rec_id__c', max_length=1300),
        ),
    ]
