# Generated by Django 3.2.13 on 2023-04-02 07:58

from django.db import migrations
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opscentre_usermanagement_api', '0021_auto_20230401_0417'),
    ]

    operations = [
        migrations.AddField(
            model_name='opsteam',
            name='ops_id',
            field=salesforce.fields.CharField(blank=True, db_column='TeamId__c', max_length=1300),
        ),
        migrations.AddField(
            model_name='opsteamrole',
            name='role_id',
            field=salesforce.fields.CharField(blank=True, db_column='RoleId__c', max_length=1300),
        ),
        migrations.AlterField(
            model_name='opsteam',
            name='id',
            field=salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='opsteam',
            name='record_id',
            field=salesforce.fields.CharField(blank=True, db_column='Id__c', max_length=1300),
        ),
        migrations.AlterField(
            model_name='opsteamrole',
            name='id',
            field=salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='opsteamrole',
            name='record_id',
            field=salesforce.fields.CharField(blank=True, db_column='Id__c', max_length=1300),
        ),
    ]
