# Generated by Django 3.2.13 on 2023-04-03 07:28

from django.db import migrations
import django.db.models.deletion
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement_api', '0003_candidateprofile_cand_id'),
        ('opscentre_usermanagement_api', '0022_auto_20230402_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sr_comments',
            name='recruiter',
            field=salesforce.fields.ForeignKey(db_column='Recruiter__c', on_delete=django.db.models.deletion.DO_NOTHING, to='usermanagement_api.contact', verbose_name='Contact ID'),
        ),
    ]
