# Generated by Django 3.2.13 on 2023-04-03 07:53

from django.db import migrations
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opscentre_usermanagement_api', '0023_alter_sr_comments_recruiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerq',
            name='record_id',
            field=salesforce.fields.CharField(blank=True, db_column='Id__c', max_length=1300),
        ),
        migrations.AddField(
            model_name='sr_comments',
            name='record_id',
            field=salesforce.fields.CharField(blank=True, db_column='Id__c', max_length=1300),
        ),
        migrations.AlterField(
            model_name='servicerq',
            name='id',
            field=salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='sr_comments',
            name='id',
            field=salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
