# Generated by Django 3.2.13 on 2023-04-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opscentre_usermanagement_api', '0025_auto_20230403_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sr_comments',
            old_name='time_stamp',
            new_name='dtime',
        ),
    ]
