# Generated by Django 3.2.13 on 2023-04-03 09:59

from django.db import migrations
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opscentre_usermanagement_api', '0026_rename_time_stamp_sr_comments_dtime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sr_comments',
            name='dtime',
        ),
        migrations.AddField(
            model_name='sr_comments',
            name='sf_dtime',
            field=salesforce.fields.DateTimeField(blank=True, db_column='createDt__c', null=True),
        ),
    ]
