# Generated by Django 3.2.13 on 2023-04-03 13:52

from django.db import migrations
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opscentre_usermanagement_api', '0027_auto_20230403_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerq',
            name='priority',
            field=salesforce.fields.CharField(blank=True, choices=[('Urgent', 'Urgent'), ('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], db_column='Priority__c', max_length=255, null=True, verbose_name='Priority'),
        ),
        migrations.AlterField(
            model_name='servicerq',
            name='status',
            field=salesforce.fields.CharField(choices=[('Open', 'Open'), ('In-Progress', 'In-Progress'), ('Closed', 'Closed')], db_column='Status__c', max_length=255, verbose_name='Status'),
        ),
    ]
