# Generated by Django 3.2.13 on 2023-04-04 09:10

from django.db import migrations
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opscentre_usermanagement_api', '0028_auto_20230403_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerq',
            name='sf_dtime',
            field=salesforce.fields.DateTimeField(blank=True, db_column='createDt__c', null=True),
        ),
    ]
