# Generated by Django 3.2.13 on 2023-04-05 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opscentre_usermanagement_api', '0029_servicerq_sf_dtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicerq',
            old_name='sf_dtime',
            new_name='create_dtime',
        ),
        migrations.RenameField(
            model_name='sr_comments',
            old_name='sf_dtime',
            new_name='create_dtime',
        ),
    ]
