# Generated by Django 3.2.13 on 2023-04-08 12:47

from django.db import migrations
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opscentre_usermanagement_api', '0030_auto_20230405_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerq',
            name='rq_id',
            field=salesforce.fields.CharField(blank=True, db_column='Name', max_length=1300),
        ),
    ]
