# Generated by Django 3.2.13 on 2023-04-10 06:32

from django.db import migrations
import django.db.models.manager
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('opscentre_usermanagement_api', '0031_servicerq_rq_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardCache',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', salesforce.fields.CharField(db_column='Name', max_length=80)),
                ('count', salesforce.fields.IntegerField(db_column='Count__c')),
                ('record_id', salesforce.fields.CharField(blank=True, db_column='Id__c', max_length=1300)),
                ('create_dtime', salesforce.fields.DateTimeField(blank=True, db_column='createDt__c', null=True)),
            ],
            options={
                'verbose_name': 'DashboardCache',
                'verbose_name_plural': 'DashboardCache',
                'db_table': 'DashboardCache__c',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='SchedulerInterval',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', salesforce.fields.CharField(db_column='Name', max_length=80)),
                ('interval', salesforce.fields.IntegerField(db_column='Interval__c')),
                ('record_id', salesforce.fields.CharField(blank=True, db_column='Id__c', max_length=1300)),
                ('create_dtime', salesforce.fields.DateTimeField(blank=True, db_column='createDt__c', null=True)),
            ],
            options={
                'verbose_name': 'SchedulerInterval',
                'verbose_name_plural': 'SchedulerInterval',
                'db_table': 'SchedulerInterval__c',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
