# Generated by Django 3.2.13 on 2023-03-17 08:15

from django.db import migrations
import django.db.models.deletion
import django.db.models.manager
import salesforce.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanagement_api', '0002_auto_20230317_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('auction_id', salesforce.fields.CharField(blank=True, db_column='Auction_Id__c', max_length=1300, null=True, verbose_name='Auction Id')),
                ('created_date', salesforce.fields.DateTimeField(db_column='CreatedDate')),
                ('last_modified_date', salesforce.fields.DateTimeField(db_column='LastModifiedDate')),
                ('role', salesforce.fields.CharField(blank=True, choices=[('Software Engineer', 'Software Engineer'), ('Senior Software Engineer', 'Senior Software Engineer'), ('Lead Engineer', 'Lead Engineer'), ('Senior Lead Engineer', 'Senior Lead Engineer')], db_column='Role__c', max_length=255, null=True)),
                ('system_modstamp', salesforce.fields.DateTimeField(db_column='SystemModstamp')),
                ('last_activity_date', salesforce.fields.DateField(blank=True, db_column='LastActivityDate', null=True)),
                ('last_viewed_date', salesforce.fields.DateTimeField(blank=True, db_column='LastViewedDate', null=True)),
                ('last_referenced_date', salesforce.fields.DateTimeField(blank=True, db_column='LastReferencedDate', null=True)),
                ('auction_end_date', salesforce.fields.DateField(blank=True, db_column='Auction_End_Date__c', null=True, verbose_name='Auction End Date')),
                ('base_bid', salesforce.fields.DecimalField(blank=True, db_column='Base_Bid__c', decimal_places=0, max_digits=18, null=True, verbose_name='Base Bid')),
                ('auction_stage', salesforce.fields.CharField(blank=True, choices=[('Draft', 'Draft'), ('Manager Approval', 'Manager Approval'), ('Not Approved', 'Not Approved'), ('Auction Active', 'Auction Active'), ('Vetting', 'Vetting'), ('Candidate Hired', 'Candidate Hired'), ('Auction Failed', 'Auction Failed'), ('Auction Finalized', 'Auction Finalized')], db_column='Auction_Stage__c', default=salesforce.fields.DefaultedOnCreate('Draft'), max_length=255, null=True, verbose_name='Auction Stage')),
                ('manager_approval', salesforce.fields.BooleanField(db_column='Manager_Approval__c', default=salesforce.fields.DefaultedOnCreate(), verbose_name='Manager Approval')),
                ('auction_live_date', salesforce.fields.DateField(blank=True, db_column='Auction_Live_Date__c', null=True, verbose_name='Auction Live Date')),
                ('increment_amount', salesforce.fields.DecimalField(blank=True, db_column='Increment_Amount__c', decimal_places=0, max_digits=18, null=True, verbose_name='Increment Amount')),
                ('latest_bid', salesforce.fields.DecimalField(blank=True, db_column='Latest_Bid__c', decimal_places=0, max_digits=18, null=True, verbose_name='Latest Bid')),
                ('candidate', salesforce.fields.ForeignKey(blank=True, db_column='Candidate__c', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermanagement_api.candidate')),
                ('candidate_profile', salesforce.fields.ForeignKey(db_column='Candidate_Profile__c', on_delete=django.db.models.deletion.DO_NOTHING, to='usermanagement_api.candidateprofile', verbose_name='Candidate Profile')),
            ],
            options={
                'verbose_name': 'Auction',
                'verbose_name_plural': 'Auctions',
                'db_table': 'Auction__c',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('username', salesforce.fields.CharField(db_column='Username', max_length=80)),
                ('last_name', salesforce.fields.CharField(db_column='LastName', max_length=80)),
                ('first_name', salesforce.fields.CharField(blank=True, db_column='FirstName', max_length=40, null=True)),
                ('middle_name', salesforce.fields.CharField(blank=True, db_column='MiddleName', max_length=40, null=True)),
                ('suffix', salesforce.fields.CharField(blank=True, db_column='Suffix', max_length=40, null=True)),
                ('name', salesforce.fields.CharField(db_column='Name', max_length=121, verbose_name='Full Name')),
                ('company_name', salesforce.fields.CharField(blank=True, db_column='CompanyName', max_length=80, null=True)),
                ('division', salesforce.fields.CharField(blank=True, db_column='Division', max_length=80, null=True)),
                ('department', salesforce.fields.CharField(blank=True, db_column='Department', max_length=80, null=True)),
                ('title', salesforce.fields.CharField(blank=True, db_column='Title', max_length=80, null=True)),
                ('street', salesforce.fields.TextField(blank=True, db_column='Street', null=True)),
                ('city', salesforce.fields.CharField(blank=True, db_column='City', max_length=40, null=True)),
                ('state', salesforce.fields.CharField(blank=True, db_column='State', max_length=80, null=True, verbose_name='State/Province')),
                ('postal_code', salesforce.fields.CharField(blank=True, db_column='PostalCode', max_length=20, null=True, verbose_name='Zip/Postal Code')),
                ('country', salesforce.fields.CharField(blank=True, db_column='Country', max_length=80, null=True)),
                ('latitude', salesforce.fields.DecimalField(blank=True, db_column='Latitude', decimal_places=15, max_digits=18, null=True)),
                ('longitude', salesforce.fields.DecimalField(blank=True, db_column='Longitude', decimal_places=15, max_digits=18, null=True)),
                ('geocode_accuracy', salesforce.fields.CharField(blank=True, choices=[('Address', 'Address'), ('NearAddress', 'NearAddress'), ('Block', 'Block'), ('Street', 'Street'), ('ExtendedZip', 'ExtendedZip'), ('Zip', 'Zip'), ('Neighborhood', 'Neighborhood'), ('City', 'City'), ('County', 'County'), ('State', 'State'), ('Unknown', 'Unknown')], db_column='GeocodeAccuracy', max_length=40, null=True)),
                ('address', salesforce.fields.TextField(blank=True, db_column='Address', null=True)),
                ('email', salesforce.fields.EmailField(db_column='Email', max_length=254)),
                ('email_preferences_auto_bcc', salesforce.fields.BooleanField(db_column='EmailPreferencesAutoBcc', default=False, verbose_name='AutoBcc')),
                ('email_preferences_auto_bcc_stay_in_touch', salesforce.fields.BooleanField(db_column='EmailPreferencesAutoBccStayInTouch', default=False, verbose_name='AutoBccStayInTouch')),
                ('email_preferences_stay_in_touch_reminder', salesforce.fields.BooleanField(db_column='EmailPreferencesStayInTouchReminder', default=False, verbose_name='StayInTouchReminder')),
                ('sender_email', salesforce.fields.EmailField(blank=True, db_column='SenderEmail', max_length=254, null=True, verbose_name='Email Sender Address')),
                ('sender_name', salesforce.fields.CharField(blank=True, db_column='SenderName', max_length=80, null=True, verbose_name='Email Sender Name')),
                ('signature', salesforce.fields.TextField(blank=True, db_column='Signature', null=True, verbose_name='Email Signature')),
                ('stay_in_touch_subject', salesforce.fields.CharField(blank=True, db_column='StayInTouchSubject', max_length=80, null=True, verbose_name='Stay-in-Touch Email Subject')),
                ('stay_in_touch_signature', salesforce.fields.TextField(blank=True, db_column='StayInTouchSignature', null=True, verbose_name='Stay-in-Touch Email Signature')),
                ('stay_in_touch_note', salesforce.fields.CharField(blank=True, db_column='StayInTouchNote', max_length=512, null=True, verbose_name='Stay-in-Touch Email Note')),
                ('phone', salesforce.fields.CharField(blank=True, db_column='Phone', max_length=40, null=True)),
                ('fax', salesforce.fields.CharField(blank=True, db_column='Fax', max_length=40, null=True)),
                ('mobile_phone', salesforce.fields.CharField(blank=True, db_column='MobilePhone', max_length=40, null=True, verbose_name='Mobile')),
                ('alias', salesforce.fields.CharField(db_column='Alias', max_length=8)),
                ('community_nickname', salesforce.fields.CharField(db_column='CommunityNickname', max_length=40, verbose_name='Nickname')),
                ('badge_text', salesforce.fields.CharField(blank=True, db_column='BadgeText', max_length=80, null=True, verbose_name='User Photo badge text overlay')),
                ('is_active', salesforce.fields.BooleanField(db_column='IsActive', default=salesforce.fields.DefaultedOnCreate(), verbose_name='Active')),
                ('time_zone_sid_key', salesforce.fields.CharField(db_column='TimeZoneSidKey', max_length=40, verbose_name='Time Zone')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'User',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', salesforce.fields.DateTimeField(db_column='CreatedDate')),
                ('last_modified_date', salesforce.fields.DateTimeField(db_column='LastModifiedDate')),
                ('auction', salesforce.fields.ForeignKey(db_column='Auction__c', on_delete=django.db.models.deletion.DO_NOTHING, to='auction_api.auction')),
                ('employer_details', salesforce.fields.ForeignKey(db_column='Employer_Details__c', on_delete=django.db.models.deletion.DO_NOTHING, to='usermanagement_api.account', verbose_name='Employer Details')),
            ],
            options={
                'verbose_name': 'Favourite',
                'verbose_name_plural': 'Favourites',
                'db_table': 'Favourite__c',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', salesforce.fields.DateTimeField(db_column='CreatedDate')),
                ('last_modified_date', salesforce.fields.DateTimeField(db_column='LastModifiedDate')),
                ('current_bid', salesforce.fields.DecimalField(blank=True, db_column='Current_Bid__c', decimal_places=2, max_digits=18, null=True, verbose_name='Current Bid')),
                ('bid_stage', salesforce.fields.CharField(blank=True, choices=[('Created', 'Created'), ('Interview', 'Interview'), ('Bid Won', 'Bid Won'), ('Bid lost', 'Bid lost')], db_column='Bid_Stage__c', max_length=255, null=True, verbose_name='Bid Stage')),
                ('bid_value', salesforce.fields.DecimalField(db_column='Bid_Value__c', decimal_places=0, max_digits=18, verbose_name='Bid Value')),
                ('offer_accepted', salesforce.fields.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], db_column='Offer_Accepted__c', max_length=255, null=True, verbose_name='Offer Accepted')),
                ('offer_rolled', salesforce.fields.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], db_column='Offer_Rolled__c', max_length=255, null=True, verbose_name='Offer Rolled')),
                ('rank', salesforce.fields.DecimalField(blank=True, db_column='Rank__c', decimal_places=0, max_digits=18, null=True)),
                ('bid_id', salesforce.fields.CharField(blank=True, db_column='Bid_Id__c', max_length=1300, null=True, verbose_name='Bid Id')),
                ('remarks_by_employer', salesforce.fields.TextField(blank=True, db_column='Remarks_By_Employer__c', null=True, verbose_name='Remarks By Employer')),
                ('remarks_by_candidate', salesforce.fields.TextField(blank=True, db_column='Remarks_By_Candidate__c', null=True, verbose_name='Remarks By Candidate')),
                ('auction', salesforce.fields.ForeignKey(db_column='Auction__c', on_delete=django.db.models.deletion.DO_NOTHING, related_name='bid_details', to='auction_api.auction')),
                ('employer_detail', salesforce.fields.ForeignKey(blank=True, db_column='Employer_Details__c', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermanagement_api.account', verbose_name='Employer Details')),
                ('employer_team', salesforce.fields.ForeignKey(blank=True, db_column='Employer_Team__c', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermanagement_api.contact', verbose_name='Employer Team')),
            ],
            options={
                'verbose_name': 'Bid',
                'verbose_name_plural': 'Bids',
                'db_table': 'Bid__c',
                'ordering': ['-bid_value'],
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='auction',
            name='recruiter',
            field=salesforce.fields.ForeignKey(blank=True, db_column='Recruiter__c', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='auction_recruiter_set', to='auction_api.user'),
        ),
    ]
