# Generated by Django 3.2.13 on 2023-03-28 05:52

from django.db import migrations
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auction_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='cand_id',
            field=salesforce.fields.CharField(blank=True, db_column='cand_id__c', max_length=1300, null=True, verbose_name='cand_id'),
        ),
    ]
