# Generated by Django 3.2.13 on 2022-06-14 10:41

from django.db import migrations
import django.db.models.manager
import salesforce.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', salesforce.fields.BooleanField(db_column='IsDeleted', default=False, verbose_name='Deleted')),
                ('name', salesforce.fields.CharField(blank=True, db_column='Name', default=salesforce.fields.DefaultedOnCreate(), max_length=80, null=True, verbose_name='Candidate  Name')),
                ('created_date', salesforce.fields.DateTimeField(db_column='CreatedDate')),
                ('last_modified_date', salesforce.fields.DateTimeField(db_column='LastModifiedDate')),
                ('system_modstamp', salesforce.fields.DateTimeField(db_column='SystemModstamp')),
                ('last_activity_date', salesforce.fields.DateField(blank=True, db_column='LastActivityDate', null=True)),
                ('last_viewed_date', salesforce.fields.DateTimeField(blank=True, db_column='LastViewedDate', null=True)),
                ('last_referenced_date', salesforce.fields.DateTimeField(blank=True, db_column='LastReferencedDate', null=True)),
                ('first_name', salesforce.fields.CharField(db_column='First_Name__c', max_length=255, verbose_name='First Name')),
                ('last_name', salesforce.fields.CharField(blank=True, db_column='Last_Name__c', max_length=255, null=True, verbose_name='Last Name')),
                ('username', salesforce.fields.CharField(db_column='Username__c', max_length=255, unique=True)),
                ('phone', salesforce.fields.CharField(db_column='Phone__c', max_length=40)),
                ('dob', salesforce.fields.DateField(db_column='DOB__c', verbose_name='DOB')),
                ('email', salesforce.fields.EmailField(db_column='Email__c', max_length=254)),
                ('record_id', salesforce.fields.CharField(blank=True, db_column='Record_ID__c', max_length=1300, null=True, verbose_name='Record ID')),
                ('password', salesforce.fields.CharField(db_column='Password__c', max_length=255)),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'db_table': 'Candidate__c',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
