# Generated by Django 3.2.13 on 2023-03-17 08:15

from django.db import migrations
import django.db.models.deletion
import django.db.models.manager
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', salesforce.fields.CharField(db_column='Name', max_length=255, verbose_name='Employer Name')),
                ('type', salesforce.fields.CharField(blank=True, choices=[('Service Based', 'Service Based'), ('Product Based', 'Product Based'), ('IT', 'IT'), ('Banking', 'Banking')], db_column='Type', max_length=255, null=True, verbose_name='Employer Type')),
                ('billing_address', salesforce.fields.TextField(blank=True, db_column='BillingAddress', null=True, verbose_name='Office Address')),
                ('website', salesforce.fields.URLField(blank=True, db_column='Website', null=True)),
                ('number_of_employees', salesforce.fields.IntegerField(blank=True, db_column='NumberOfEmployees', null=True, verbose_name='Total Employees')),
                ('bgv_completed', salesforce.fields.BooleanField(db_column='BGV_Completed__c', default=salesforce.fields.DefaultedOnCreate(), verbose_name='BGV Completed')),
                ('employer_team_count', salesforce.fields.DecimalField(blank=True, db_column='Employer_Team_Count__c', decimal_places=0, default=salesforce.fields.DefaultedOnCreate(), max_digits=18, null=True, verbose_name='Employer Team Count')),
                ('employer_details_id', salesforce.fields.CharField(blank=True, db_column='Employer_Details_Id__c', max_length=1300, null=True, verbose_name='Employer Details Id')),
            ],
            options={
                'verbose_name': 'Employer Detail',
                'verbose_name_plural': 'Employer Details',
                'db_table': 'Account',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', salesforce.fields.CharField(db_column='LastName', max_length=80)),
                ('first_name', salesforce.fields.CharField(blank=True, db_column='FirstName', max_length=40, null=True)),
                ('mobile_phone', salesforce.fields.CharField(blank=True, db_column='MobilePhone', max_length=40, null=True)),
                ('email', salesforce.fields.EmailField(blank=True, db_column='Email', max_length=254, null=True)),
                ('email_verified', salesforce.fields.BooleanField(db_column='Email_Verified__c', default=salesforce.fields.DefaultedOnCreate(), verbose_name='Email Verified')),
                ('password', salesforce.fields.CharField(db_column='Password__c', max_length=255)),
                ('role', salesforce.fields.CharField(blank=True, choices=[('Admin', 'Admin'), ('Team Member', 'Team Member')], db_column='Role__c', max_length=255, null=True)),
                ('member_id', salesforce.fields.CharField(blank=True, db_column='Member_Id__c', max_length=1300, null=True, verbose_name='Member Id')),
                ('status', salesforce.fields.CharField(blank=True, choices=[('Active', 'Active'), ('Inactive', 'Inactive')], db_column='Status__c', default=salesforce.fields.DefaultedOnCreate('Active'), max_length=255, null=True)),
                ('account', salesforce.fields.ForeignKey(blank=True, db_column='AccountId', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermanagement_api.account', verbose_name='Employer Name')),
            ],
            options={
                'verbose_name': 'Employer Team',
                'verbose_name_plural': 'Employer Teams',
                'db_table': 'Contact',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('name', salesforce.fields.CharField(blank=True, db_column='Name', default=salesforce.fields.DefaultedOnCreate(), max_length=80, null=True, verbose_name='Employer Name')),
                ('created_date', salesforce.fields.DateTimeField(db_column='CreatedDate')),
                ('last_modified_date', salesforce.fields.DateTimeField(db_column='LastModifiedDate')),
                ('communication_email', salesforce.fields.EmailField(db_column='Communication_Email__c', max_length=254, unique=True, verbose_name='Communication Email')),
                ('screening_stage', salesforce.fields.CharField(blank=True, choices=[('Draft', 'Draft'), ('Background Check', 'Background Check'), ('Proposal', 'Proposal'), ('Negotiation', 'Negotiation'), ('Accept', 'Accept'), ('Reject', 'Reject')], db_column='Screening_Stage__c', max_length=255, null=True, verbose_name='Screening Stage')),
                ('phone', salesforce.fields.CharField(db_column='Phone__c', max_length=40)),
                ('website', salesforce.fields.URLField(db_column='Website__c')),
                ('email_verification', salesforce.fields.BooleanField(db_column='Email_Verification__c', default=salesforce.fields.DefaultedOnCreate(), verbose_name='Email Verification')),
                ('record_id', salesforce.fields.CharField(blank=True, db_column='Record_ID__c', max_length=1300, null=True, verbose_name='Record ID')),
                ('password', salesforce.fields.CharField(blank=True, db_column='Password__c', max_length=255, null=True)),
                ('ceo_validated', salesforce.fields.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], db_column='CEO_Validated__c', max_length=255, null=True, verbose_name='CEO Validated')),
            ],
            options={
                'verbose_name': 'Employer',
                'verbose_name_plural': 'Employers',
                'db_table': 'Employer__c',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='last_activity_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='last_modified_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='last_referenced_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='last_viewed_date',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='name',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='system_modstamp',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='username',
        ),
        migrations.AddField(
            model_name='candidate',
            name='email_verification',
            field=salesforce.fields.BooleanField(db_column='Email_Verification__c', default=salesforce.fields.DefaultedOnCreate(), verbose_name='Email Verification'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='screening_stages',
            field=salesforce.fields.CharField(blank=True, choices=[('Draft', 'Draft'), ('Email Verified', 'Email Verified'), ('Profile Created', 'Profile Created')], db_column='Screening_Stages__c', default=salesforce.fields.DefaultedOnCreate('Draft'), max_length=255, null=True, verbose_name='Screening Stages'),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='email',
            field=salesforce.fields.EmailField(db_column='Email__c', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='record_id',
            field=salesforce.fields.CharField(blank=True, db_column='Id__c', max_length=1300),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', salesforce.fields.DateTimeField(db_column='CreatedDate')),
                ('message', salesforce.fields.TextField(blank=True, db_column='Message__c', null=True)),
                ('read', salesforce.fields.BooleanField(db_column='Read__c', default=salesforce.fields.DefaultedOnCreate())),
                ('employer_team', salesforce.fields.ForeignKey(blank=True, db_column='Employer_Team__c', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermanagement_api.contact', verbose_name='Employer Team')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'Notification__c',
                'ordering': ['-created_date'],
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='EmployerProfile',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', salesforce.fields.DateTimeField(db_column='CreatedDate')),
                ('communication_email', salesforce.fields.CharField(blank=True, db_column='Communication_Email__c', max_length=1300, null=True, verbose_name='Communication Email')),
                ('phone', salesforce.fields.CharField(blank=True, db_column='Phone__c', max_length=1300, null=True)),
                ('employer', salesforce.fields.ForeignKey(blank=True, db_column='Employer__c', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermanagement_api.employer')),
            ],
            options={
                'verbose_name': 'Employer Profile',
                'verbose_name_plural': 'Employer Profiles',
                'db_table': 'Employer_Profile__c',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', salesforce.fields.SalesforceAutoField(auto_created=True, db_column='Id', primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', salesforce.fields.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Not Disclosed', 'Not Disclosed')], db_column='Gender__c', max_length=255, null=True)),
                ('current_ctc', salesforce.fields.CharField(blank=True, db_column='Current_CTC__c', max_length=255, null=True, verbose_name='Current CTC')),
                ('candidate_email', salesforce.fields.CharField(blank=True, db_column='Candidate_Email__c', max_length=1300, null=True, verbose_name='Candidate Email')),
                ('first_name', salesforce.fields.CharField(blank=True, db_column='First_Name__c', max_length=1300, null=True, verbose_name='First Name')),
                ('last_name', salesforce.fields.CharField(blank=True, db_column='Last_Name__c', max_length=1300, null=True, verbose_name='Last Name')),
                ('resume_url', salesforce.fields.CharField(blank=True, db_column='Resume_URL__c', max_length=255, null=True, verbose_name='Resume URL')),
                ('about', salesforce.fields.TextField(blank=True, db_column='About__c', null=True)),
                ('experience', salesforce.fields.TextField(blank=True, db_column='Experience__c', null=True)),
                ('projects', salesforce.fields.TextField(blank=True, db_column='Projects__c', null=True)),
                ('certifications', salesforce.fields.TextField(blank=True, db_column='Certifications__c', null=True)),
                ('accomplishments', salesforce.fields.TextField(blank=True, db_column='Accomplishments__c', null=True)),
                ('links', salesforce.fields.TextField(blank=True, db_column='Links__c', null=True)),
                ('current_employer', salesforce.fields.CharField(blank=True, db_column='Current_Employer__c', max_length=255, null=True, verbose_name='Current Employer')),
                ('preferred_work_location', salesforce.fields.CharField(blank=True, db_column='Preferred_Work_Location__c', max_length=255, null=True, verbose_name='Preferred Work Location')),
                ('current_role', salesforce.fields.CharField(blank=True, db_column='Current_Role__c', max_length=255, null=True, verbose_name='Current Role')),
                ('expected_role', salesforce.fields.CharField(blank=True, db_column='Expected_Role__c', max_length=255, null=True, verbose_name='Expected Role')),
                ('current_address', salesforce.fields.TextField(blank=True, db_column='Current_Address__c', null=True, verbose_name='Current Address')),
                ('permanent_address', salesforce.fields.TextField(blank=True, db_column='Permanent_Address__c', null=True, verbose_name='Permanent Address')),
                ('relevant_experience', salesforce.fields.CharField(blank=True, db_column='Relevant_Experience__c', max_length=255, null=True, verbose_name='Relevant Experience')),
                ('total_experience', salesforce.fields.CharField(blank=True, db_column='Total_Experience__c', max_length=255, null=True, verbose_name='Total Experience')),
                ('notice_period', salesforce.fields.CharField(blank=True, db_column='Notice_Period__c', max_length=255, null=True, verbose_name='Notice Period')),
                ('screening_stages', salesforce.fields.CharField(blank=True, choices=[('Profile Created', 'Profile Created'), ('Request for Auction', 'Request for Auction'), ('BGV & Assessment', 'BGV & Assessment'), ('Ready for Auction', 'Ready for Auction')], db_column='Screening_Stages__c', default=salesforce.fields.DefaultedOnCreate('Profile Created'), max_length=255, null=True, verbose_name='Screening Stages')),
                ('auction_availability', salesforce.fields.BooleanField(db_column='Auction_Availability__c', default=salesforce.fields.DefaultedOnCreate(), verbose_name='Auction Availability')),
                ('background_verification', salesforce.fields.BooleanField(db_column='Background_Verification__c', default=salesforce.fields.DefaultedOnCreate(), verbose_name='Background Verification')),
                ('assessment', salesforce.fields.CharField(blank=True, choices=[('Not Attempted', 'Not Attempted'), ('Pass', 'Pass'), ('Failed', 'Failed')], db_column='Assessment__c', default=salesforce.fields.DefaultedOnCreate('Not Attempted'), max_length=255, null=True)),
                ('record_id', salesforce.fields.CharField(blank=True, db_column='Id__c', max_length=1300, null=True)),
                ('skills', salesforce.fields.CharField(blank=True, db_column='Skills__c', max_length=255, null=True)),
                ('education', salesforce.fields.TextField(blank=True, db_column='Education__c', null=True)),
                ('candidate_phone', salesforce.fields.CharField(blank=True, db_column='Candidate_Phone__c', max_length=1300, null=True, verbose_name='Candidate Phone')),
                ('dob', salesforce.fields.CharField(blank=True, db_column='DOB__c', max_length=255, null=True, verbose_name='DOB')),
                ('candidate', salesforce.fields.ForeignKey(blank=True, db_column='Candidate__c', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usermanagement_api.candidate')),
            ],
            options={
                'verbose_name': 'Candidate Profile',
                'verbose_name_plural': 'Candidate Profiles',
                'db_table': 'Candidate_Profile__c',
                'abstract': False,
                'base_manager_name': 'base_manager',
            },
            managers=[
                ('base_manager', django.db.models.manager.Manager()),
            ],
        ),
    ]
