# Generated by Django 3.2.13 on 2023-03-23 14:58

from django.db import migrations
import salesforce.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement_api', '0002_auto_20230317_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='cand_id',
            field=salesforce.fields.CharField(blank=True, db_column='cand_id__c', max_length=255, null=True, verbose_name='cand_id'),
        ),
    ]
